### PR TITLE
Add ability to specify HOMEDIR and a test suite

### PR DESCRIPTION
**Pull request by athornton**

### CODE REVIEW

**Comment by athornton** [comment]
I think I need to be more careful with directory creation: I can't just set the bottom layer to 0700, I need to remember which directories I created and chmod each one of those, which means I can't just do a mkdir -p.

**Comment by athornton** [comment]
Or, wait, with umask I can guarantee that, can't I?

**Review by rra — COMMENTED** [review]
This is beyond my complexity threshold for what I think makes sense to do in shell. I don't really want to think hard enough to figure out what all those cuts and revs and whatnot are doing and whether all the quoting is correct, particularly now that there's a test suite in shell. (For example, I'm fairly sure the assignments to `r_uid` and `r_gid` need to quote `$HOMEDIR` in case it contains spaces.)

Can we switch to Python? I know that means a larger container but we use the current Python slim container as a base for basically everything so it's highly likely it's cached. We can just not update that container with new Debian packages and rely on the fact that new Python containers are built regularly and dependabot will switch us to them. We can test performance if needed but I bet it won't be a problem.

Since this is a major version upgrade and there are a bunch of other incompatible changes in Nublado, I think we should drop support for the home directory not being passed in, and I'd also like to standardize the protocol used to communicate with init containers to namespace our environment variables. The latter isn't a big deal but since we're making changes anyway, we may as well follow best practices for environment variables and use `NUBLADO_UID`, `NUBLADO_GID`, and `NUBLADO_HOME` or something like that as the interface.

**Comment by athornton** [comment]
Well, if we're gonna do it that way, then may as well transplant it over into the monorepo where we'll have our python tooling anyway.

**Pull request closed without merging**
